$axure.loadCurrentPage({
  "url":"colors.html",
  "generationDate":new Date(1382343932351.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"3cfea15e21ec4ed08ab9d47cdac6199d",
    "type":"Axure:Page",
    "name":"colors",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"26b98a9212d04f6097ff4d3db21550d0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFDFF5FF,
              "opacity":1},
            "location":{
              "x":10,
              "y":60},
            "size":{
              "width":414,
              "height":190},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e9d8789a2e540d38c9b06bc0c2351bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFDFF5FF,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":60},
                "size":{
                  "width":414,
                  "height":190},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/colors/u0.png"}},
{
          "id":"607d2207992d44e2b9788f4cf42d7f74",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":528,
              "y":71},
            "size":{
              "width":102,
              "height":89},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9ebb1d2fc2442bd970d2dd055da92b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":71},
                "size":{
                  "width":102,
                  "height":89},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/colors/u2.png"}},
{
          "id":"9011bd1e39634b84b81f56a1d7de55c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":30},
            "size":{
              "width":150,
              "height":29},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fc5ae2844f44da9b66330eae84e13cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":30},
                "size":{
                  "width":150,
                  "height":29},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e3f46bae9fc452491f7983980d1aa5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF15A8E8},
            "location":{
              "x":500,
              "y":180},
            "size":{
              "width":180,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bbf556915874625bfd18c33f13e4b1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF15A8E8},
                "location":{
                  "x":500,
                  "y":180},
                "size":{
                  "width":180,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/colors/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "26b98a9212d04f6097ff4d3db21550d0":{
      "scriptId":"u0"},
    "6e9d8789a2e540d38c9b06bc0c2351bf":{
      "scriptId":"u1"},
    "607d2207992d44e2b9788f4cf42d7f74":{
      "scriptId":"u2"},
    "d9ebb1d2fc2442bd970d2dd055da92b9":{
      "scriptId":"u3"},
    "9011bd1e39634b84b81f56a1d7de55c2":{
      "scriptId":"u4"},
    "4fc5ae2844f44da9b66330eae84e13cd":{
      "scriptId":"u5"},
    "8e3f46bae9fc452491f7983980d1aa5e":{
      "scriptId":"u6"},
    "0bbf556915874625bfd18c33f13e4b1b":{
      "scriptId":"u7"}}});