$axure.loadCurrentPage({
  "url":"pdf.html",
  "generationDate":new Date(1382343932365.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"2b065de6e2d74eb486094da03218fafe",
    "type":"Axure:Page",
    "name":"pdf",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"97b4c117b30b4e00959662ac798e83f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":40},
            "size":{
              "width":620,
              "height":620}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7e9af6332404b4290aeb350631535ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":40},
                "size":{
                  "width":620,
                  "height":620}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pdf/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "97b4c117b30b4e00959662ac798e83f6":{
      "scriptId":"u0"},
    "c7e9af6332404b4290aeb350631535ec":{
      "scriptId":"u1"}}});